version: '3'

services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    networks:
      - devops_net

  jenkins:
    build: ./jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - devops_net

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - devops_net

volumes:
  jenkins_home:

networks:
  devops_net:
